language: node_js
dist: bionic
node_js:
  - "8"
  - "6"
  - "4"
addons:
  apt: mssql-server
before_script:
  - sqlcmd -c 'create database TestDB;' -U SA -P Password1
script: yarn test

notifications:
  email:
    on_success: never
