language: node_js
node_js:
  - "8"
  - "6"
  - "4"
addons:
  apt:
    packages:
      - sqlcmd
before_script:
  - sqlcmd -c 'create database TestDB;' -U SA -P Password1
script: npm test
after_success: npm run coverage
notifications:
  email:
    on_success: never
